#!/usr/bin/env bash

set -euo pipefail

: ${REPO:="$(pwd)"}
: ${CC:=clang}
CFLAGS="-Wall -Wextra -Werror -Wnull-dereference -Wformat=2
-Wshadow -Wsign-conversion -Wfloat-equal -Wswitch-enum -Wmissing-prototypes
-Wdeprecated-declarations -std=c11 -g"
LDFLAGS=""

cc() {
	echo "CC	$@"
	$CC $CFLAGS $LDFLAGS $@
}

execute() {
	echo "EXEC	$@"
	$@
	echo "exit code $?"
}

case "${1:-test}" in
	test)
		cc -I. -D_POSIX_C_SOURCE=200112L test.c -o test

		execute ./test
		;;

	bench)
		cc -I. -O3 bench.c -o bench
		execute ./bench
		;;

	compile_flags.txt)
		echo $CFLAGS -Isrc/ -DXIO_IMPLEMENTATION -D_POSIX_C_SOURCE=200112L \
			| tr ' ' '\n' > compile_flags.txt
		;;

	*)
		echo "unknown command: '${1-}'" >&2
		exit 1
		;;
esac
