#!/usr/bin/env bash

set -euo pipefail

: ${REPO:="$(pwd)"}
: ${CC:=clang}
CFLAGS="-Wall -Wextra -Werror -Wnull-dereference -Wformat=2
-Wshadow -Wsign-conversion -Wfloat-equal -Wswitch-enum -Wmissing-prototypes
-Wdeprecated-declarations -std=c11 -g"
LDFLAGS=""

cc() {
	echo "CC	$@"
	$CC $CFLAGS $LDFLAGS $@
}

execute() {
	echo "EXEC	$@"
	$@
	echo "exit code $?"
}

bundle() {
	awk 'BEGIN { print "/**" } { print "* " $0 } END { print "**/" }' < "$REPO"/LICENSE
	cat <<EOF
#ifndef LIBXIO_H_INCLUDE
#define LIBXIO_H_INCLUDE

$(cat "$REPO"/src/libxio.h | grep -v '#include "')

#ifdef LIBXIO_IMPLEMENTATION
#ifdef XIO_UNIX
$(cat "$REPO"/src/unix/fs.c | grep -v '#include "')
#endif /* XIO_UNIX */
#endif /* LIBXIO_IMPLEMENTATION */

#endif /* LIBXIO_H_INCLUDE */
EOF
}

case "${1:-bundle}" in
	bundle)
		bundle > libxio.h
		;;

	test)
		for f in ./tests/*.c; do
			cc -I. -D_POSIX_C_SOURCE=200809L $f -o ${f%%.c}
			execute ${f%%.c}
		done
		;;

	bench)
		cc -I. -O3 bench.c -o bench
		execute ./bench
		;;

	compile_flags.txt)
		echo $CFLAGS -Isrc/ -DXIO_IMPLEMENTATION -D_POSIX_C_SOURCE=200809L \
			| tr ' ' '\n' > compile_flags.txt
		;;

	*)
		echo "unknown command: '${1-}'" >&2
		exit 1
		;;
esac
